import { IRoute } from 'umi-types';
import loginRoutes from './general-routes/login';
import system from './general-routes/system';
import exception from './general-routes/exception';
import businessRoutes from './business-routes';

// 路由
export const routes: IRoute[] = [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      loginRoutes,
      {
        path: '/',
        component: '../layouts/BasicLayout',
        routes: [
          {
            path: '/',
            component: './Welcome',
          },
          ...businessRoutes,
          exception,
          system,
        ],
      },
    ],
  },
];

export const omitRoutes = [
  {
    id: 1001,
    type: 'others',
    key: '/system',
    name: '系统管理',
    parentid: 0,
    isMenu: true,
    active: null,
  },
  {
    id: 1002,
    type: 'others',
    key: '/system/user',
    name: '用户管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1003,
    type: 'others',
    key: '/system/menu',
    name: '菜单管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1004,
    type: 'others',
    key: '/system/role',
    name: '角色管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1005,
    type: 'others',
    key: '/system/task',
    name: '任务管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1006,
    type: 'others',
    key: '/system/audit',
    name: '审计管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1007,
    type: 'others',
    key: '/system/version',
    name: '版本管理',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1009,
    type: 'others',
    key: '/system/config-form',
    name: '表单配置',
    parentid: 1001,
    isMenu: true,
    active: null,
  },
  {
    id: 1010,
    type: 'others',
    key: '/system/config-form/sections',
    name: '模块配置',
    parentid: 1009,
    isMenu: true,
    active: null,
  },
  {
    id: 1011,
    type: 'others',
    key: '/system/config-form/descriptions',
    name: '详情配置',
    parentid: 1009,
    isMenu: true,
    active: null,
  },
  {
    id: 999,
    type: 'others',
    key: '/account/settings',
    name: '个人设置',
    parentid: 0,
    active: null,
  },
  {
    id: 998,
    type: 'others',
    key: '/pregnancies/physical-exam/edit',
    name: '体格检查',
    parentid: 24,
    active: null,
  },
  {
    id: 599,
    type: 'others',
    key: '/statistics',
    isMenu: true,
    active: null,
  },
  {
    id: 419,
    type: 'others',
    key: '/debility-children',
    isMenu: true,
    active: null,
  },
  {
    id: 399,
    type: 'others',
    key: '/neonatal-screening',
    isMenu: true,
    active: null,
  },
  {
    id: 379,
    type: 'others',
    key: '/child-death',
    isMenu: true,
    active: null,
  },
  {
    id: 35,
    type: 'others',
    key: '/child-examination',
    name: '儿童健康提价管理',
    isMenu: true,
    active: null,
  },
  {
    id: 351,
    type: 'others',
    key: '/child-examination/archive',
    name: '儿童档案',
    isMenu: true,
    active: null,
  },
  {
    id: 352,
    type: 'others',
    key: '/child-examination/examination-record',
    name: '健康体检记录',
    isMenu: true,
    active: null,
  },
  {
    id: 353,
    type: 'others',
    key: '/child-examination/examination-edit',
    name: '健康体检登记',
    isMenu: true,
    active: null,
  },
  {
    id: 353,
    type: 'others',
    key: '/child-examination/birth-charts',
    name: 'chart图表',
    isMenu: true,
    active: null,
  },
  {
    id: 339,
    type: 'others',
    key: '/high-risk-children',
    isMenu: true,
    active: null,
  },
  {
    id: 319,
    type: 'others',
    key: '/hearing-screening',
    isMenu: true,
    active: null,
  },
  {
    id: 298,
    type: 'others',
    key: '/deliver-management',
    name: '分娩管理',
    parentid: 0,
    isMenu: true,
    active: null,
  },
  {
    id: 297,
    type: 'others',
    key: '/deliver-management/labour-record',
    name: '分娩记录',
    parentid: 998,
    isMenu: true,
    active: null,
  },
  {
    id: 297,
    type: 'others',
    key: '/deliver-management/labour-record/add',
    name: '添加分娩记录',
    active: null,
  },
  {
    id: 297,
    type: 'others',
    key: '/deliver-management/labour-record/edit',
    name: '修改分娩记录',
    active: null,
  },
  {
    id: 296,
    type: 'others',
    key: '/deliver-management/admission',
    name: '入院登记',
    isMenu: true,
    active: null,
  },
  {
    id: 600,
    type: 'others',
    key: '/deliver-management/admission/add',
    name: '添加入院登记',
    active: null,
  },
  {
    id: 601,
    type: 'others',
    key: '/deliver-management/admission/edit',
    name: '修改入院登记',
    active: null,
  },
  {
    id: 620,
    type: 'others',
    key: '/deliver-management/admission/deliver-edit',
    name: '查看病例',
    active: null,
  },
  {
    id: 295,
    type: 'others',
    key: '/deliver-management/labour-record',
    name: '分娩记录',
    isMenu: true,
    active: null,
  },
  {
    id: 602,
    type: 'others',
    key: '/deliver-management/labour-record/add',
    name: '添加分娩记录',
    active: null,
  },
  {
    id: 603,
    type: 'others',
    key: '/deliver-management/labour-record/edit',
    name: '修改分娩记录',
    active: null,
  },
  {
    id: 294,
    type: 'others',
    key: '/deliver-management/nursing-record',
    name: '护理记录',
    isMenu: true,
    active: null,
  },
  {
    id: 604,
    type: 'others',
    key: '/deliver-management/nursing-record/add',
    name: '添加护理记录',
    active: null,
  },
  {
    id: 605,
    type: 'others',
    key: '/deliver-management/nursing-record/edit',
    name: '修改护理记录',
    active: null,
  },
  {
    id: 293,
    type: 'others',
    key: '/deliver-management/predelivery',
    isMenu: true,
    name: '待产记录',
    active: null,
  },
  {
    id: 606,
    type: 'others',
    key: '/deliver-management/predelivery/add',
    name: '添加待产记录',
    active: null,
  },
  {
    id: 607,
    type: 'others',
    key: '/deliver-management/predelivery/edit',
    name: '修改待产记录',
    active: null,
  },
  {
    id: 292,
    type: 'others',
    name: '剖宫产记录',
    key: '/deliver-management/caesarean-delivery',
    isMenu: true,
    active: null,
  },
  {
    id: 608,
    type: 'others',
    key: '/deliver-management/caesarean-delivery/add',
    name: '添加剖宫产记录',
    active: null,
  },
  {
    id: 609,
    type: 'others',
    key: '/deliver-management/caesarean-delivery/edit',
    name: '修改剖宫产记录',
    active: null,
  },
  {
    id: 291,
    type: 'others',
    key: '/deliver-management/neonate-record',
    isMenu: true,
    name: '新生儿记录',
    active: null,
  },
  {
    id: 610,
    type: 'others',
    key: '/deliver-management/neonate-record/add',
    name: '添加新生儿记录',
    active: null,
  },
  {
    id: 611,
    type: 'others',
    key: '/deliver-management/neonate-record/edit',
    name: '修改新生儿记录',
    active: null,
  },
  {
    id: 290,
    type: 'others',
    key: '/deliver-management/postpartum-visit',
    name: '产后访视',
    isMenu: true,
    active: null,
  },
  {
    id: 612,
    type: 'others',
    key: '/deliver-management/postpartum-visit/add',
    name: '添加产后访视',
    active: null,
  },
  {
    id: 613,
    type: 'others',
    key: '/deliver-management/postpartum-visit/edit',
    name: '修改产后访视',
    active: null,
  },
  {
    id: 279,
    type: 'others',
    key: '/postpartum-visit',
    active: null,
    isMenu: true,
  },
  {
    id: 259,
    type: 'others',
    key: '/maternal-death',
    active: null,
    isMenu: true,
  },
  {
    id: 239,
    type: 'others',
    key: '/pmtct',
    active: null,
    isMenu: true,
  },
  {
    id: 219,
    type: 'others',
    key: '/birth-defect',
    active: null,
    isMenu: true,
  },
  {
    id: 199,
    type: 'others',
    key: '/premarital-care',
    name: '婚前保健',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 198,
    type: 'others',
    key: '/premarital-care/wife',
    name: '女方档案',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 197,
    type: 'others',
    key: '/premarital-care/husband',
    name: '男方档案',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 196,
    type: 'others',
    key: '/premarital-care/visit-wife',
    name: '女方婚前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 195,
    type: 'others',
    key: '/premarital-care/visit-husband',
    name: '男方婚前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 194,
    type: 'others',
    key: '/premarital-care/certification',
    name: '婚前医学证明',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 194,
    type: 'others',
    key: '/premarital-care/statistics',
    name: '婚检统计',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 179,
    type: 'others',
    key: '/gynecological-diseases',
    name: '妇女病普查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 178,
    type: 'others',
    key: '/gynecological-diseases/women',
    name: '档案管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 177,
    type: 'others',
    key: '/gynecological-diseases/examination',
    name: '妇女病普查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 176,
    type: 'others',
    key: '/gynecological-diseases/cervical-cancer-screen',
    name: '宫颈癌筛查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 175,
    type: 'others',
    key: '/gynecological-diseases/breast-cancer-screen',
    name: '乳腺癌筛查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 159,
    type: 'others',
    key: '/prenatal-visit',
    name: '产前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 158,
    type: 'others',
    key: '/prenatal-visit/pregnancy',
    name: '孕册管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 157,
    type: 'others',
    key: '/prenatal-visit/initial',
    name: '首诊管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 156,
    type: 'others',
    key: '/prenatal-visit/return',
    name: '复诊管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 155,
    type: 'others',
    key: '/prenatal-visit/statistics',
    name: '统计报表',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 139,
    type: 'others',
    key: '/high-risk-management',
    name: '高危孕妇管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 138,
    type: 'others',
    key: '/high-risk-management/highrisk',
    name: '高危登记',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 137,
    type: 'others',
    key: '/high-risk-management/followup',
    name: '高危随访',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 137,
    type: 'others',
    key: '/high-risk-management/statistics',
    name: '统计报表',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 119,
    type: 'others',
    key: '/prenatal-screening',
    active: null,
    isMenu: true,
  },
  {
    id: 99,
    type: 'others',
    key: '/prenatal-diagnosis',
    active: null,
    isMenu: true,
  },
  {
    id: 98,
    type: 'others',
    key: '/prenatal-diagnosis/medical-record',
    active: null,
    isMenu: false
  },
  {
    id: 97,
    type: 'others',
    key: '/prenatal-diagnosis/operation-record',
    active: null,
    isMenu: true
  },
  {
    id: 96,
    type: 'others',
    key: '/prenatal-diagnosis/admission',
    active: null,
    isMenu: true
  },
  {
    id: 95,
    type: 'others',
    key: '/prenatal-diagnosis/main',
    active: null,
    isMenu: false
  },
  {
    id: 94,
    type: 'others',
    key: '/prenatal-diagnosis/new-patient',
    active: null,
    isMenu: true
  },
  {
    id: 93,
    type: 'others',
    key: '/prenatal-diagnosis/medical-record-form',
    active: null,
    isMenu: false
  }
];
