import { IRoute } from 'umi-types';
import loginRoutes from './general-routes/login';
import system from './general-routes/system';
import exception from './general-routes/exception';
import businessRoutes from './business-routes';

// 路由
export const routes: IRoute[] = [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      loginRoutes,
      {
        path: '/',
        component: '../layouts/BasicLayout',
        routes: [
          {
            path: '/',
            component: './Welcome',
          },
          ...businessRoutes,
          exception,
          system,
        ],
      },
    ],
  },
];

export const omitRoutes = [
  {
    id: 999,
    type: 'others',
    key: '/account/settings',
    name: '个人设置',
    parentid: 0,
    active: null,
  },
  {
    id: 998,
    type: 'others',
    key: '/pregnancies/physical-exam/edit',
    name: '体格检查',
    parentid: 24,
    active: null,
  },
  {
    id: 998,
    type: 'others',
    key: '/deliver-management',
    name: '分娩管理',
    parentid: 0,
    isMenu: true,
    active: null,
  },
  {
    id: 997,
    type: 'others',
    key: '/deliver-management/deliver-form',
    name: '分娩记录',
    parentid: 998,
    isMenu: true,
    active: null,
  },
  {
    id: 996,
    type: 'others',
    key: '/form-test',
    name: '表单测试',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 995,
    type: 'others',
    key: '/ai-mei-yi',
    name: '艾梅乙专案上报管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 994,
    type: 'others',
    key: '/birth-defect',
    name: '出生缺陷登记',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 993,
    type: 'others',
    key: '/child-death-report',
    name: '儿童死亡报告管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 992,
    type: 'others',
    name: '儿童健康体检',
    key: '/child-examination',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 991,
    type: 'others',
    name: '高危儿管理',
    key: '/high-risk-children',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 990,
    type: 'others',
    key: '/high-risk-pregnant-women',
    parentid: 0,
    name: '高危孕产妇管理',
    active: null,
    isMenu: true,
  },
  {
    id: 989,
    type: 'others',
    name: '儿童听力筛查',
    key: '/hearing-screening',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 988,
    type: 'others',
    name: '高危儿管理',
    key: '/high-risk-children',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 987,
    type: 'others',
    name: '孕产妇死亡报告',
    key: '/maternal-mortality-report',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 986,
    name: '新生儿疾病筛查',
    type: 'others',
    key: '/neonatal-screening',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 985,
    type: 'others',
    name: '营养性疾病儿童管理',
    key: '/nutritional-diseases',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 984,
    type: 'others',
    name: '产后42天访视',
    key: '/postpartum-visit',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 983,
    type: 'others',
    name: '婚前保健',
    key: '/premarital-care',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 982,
    type: 'others',
    name: '产前诊断',
    key: '/prenatal-diagnosis',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 981,
    type: 'others',
    name: '产前检查',
    key: '/prenatal-examination',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 980,
    type: 'others',
    name: '产前筛查',
    key: '/prenatal-screening',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 979,
    name: '统计查询',
    type: 'others',
    key: '/statistical-query',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 978,
    type: 'others',
    name: '妇女病普查管理',
    key: '/women-diseases',
    parentid: 0,
    active: null,
    isMenu: true,
  },
];
