import { IRoute } from 'umi-types';
import loginRoutes from './general-routes/login';
import system from './general-routes/system';
import exception from './general-routes/exception';
import businessRoutes from './business-routes';

// 路由
export const routes: IRoute[] = [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      loginRoutes,
      {
        path: '/',
        component: '../layouts/BasicLayout',
        routes: [
          {
            path: '/',
            component: './Welcome',
          },
          ...businessRoutes,
          exception,
          system,
        ],
      },
    ],
  },
];

export const omitRoutes = [
  {
    id: 999,
    type: 'others',
    key: '/account/settings',
    name: '个人设置',
    parentid: 0,
    active: null,
  },
  {
    id: 998,
    type: 'others',
    key: '/pregnancies/physical-exam/edit',
    name: '体格检查',
    parentid: 24,
    active: null,
  },
  {
    id: 996,
    type: 'others',
    key: '/form-test',
    name: '表单测试',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 599,
    type: 'others',
    key: '/statistics',
    isMenu: true,
    active: null,
  },
  {
    id: 419,
    type: 'others',
    key: '/debility-children',
    isMenu: true,
    active: null,
  },
  {
    id: 399,
    type: 'others',
    key: '/neonatal-screening',
    isMenu: true,
    active: null,
  },
  {
    id: 379,
    type: 'others',
    key: '/child-death',
    isMenu: true,
    active: null,
  },
  {
    id: 359,
    type: 'others',
    key: '/child-examination',
    isMenu: true,
    active: null,
  },
  {
    id: 339,
    type: 'others',
    key: '/high-risk-children',
    isMenu: true,
    active: null,
  },
  {
    id: 319,
    type: 'others',
    key: '/hearing-screening',
    isMenu: true,
    active: null,
  },
  {
    id: 298,
    type: 'others',
    key: '/deliver-management',
    name: '分娩管理',
    parentid: 0,
    isMenu: true,
    active: null,
  },
  {
    id: 297,
    type: 'others',
    key: '/deliver-management/deliver-form',
    name: '分娩记录',
    parentid: 998,
    isMenu: true,
    active: null,
  },
  {
    id: 296,
    type: 'others',
    key: '/deliver-management/admission',
    isMenu: true,
    active: null,
  },
  {
    id: 295,
    type: 'others',
    key: '/deliver-management/labour-record',
    isMenu: true,
    active: null,
  },
  {
    id: 294,
    type: 'others',
    key: '/deliver-management/nursing-record',
    isMenu: true,
    active: null,
  },
  {
    id: 293,
    type: 'others',
    key: '/deliver-management/predelivery',
    isMenu: true,
    active: null,
  },
  {
    id: 292,
    type: 'others',
    key: '/deliver-management/caesarean-delivery',
    isMenu: true,
    active: null,
  },
  {
    id: 291,
    type: 'others',
    key: '/deliver-management/neonate-record',
    isMenu: true,
    active: null,
  },
  {
    id: 290,
    type: 'others',
    key: '/deliver-management/postpartum-visit',
    isMenu: true,
    active: null,
  },
  {
    id: 279,
    type: 'others',
    key: '/postpartum-visit',
    active: null,
    isMenu: true,
  },
  {
    id: 259,
    type: 'others',
    key: '/maternal-death',
    active: null,
    isMenu: true,
  },
  {
    id: 239,
    type: 'others',
    key: '/pmtct',
    active: null,
    isMenu: true,
  },
  {
    id: 219,
    type: 'others',
    key: '/birth-defect',
    active: null,
    isMenu: true,
  },
  {
    id: 199,
    type: 'others',
    key: '/premarital-care',
    name: '婚前保健',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 198,
    type: 'others',
    key: '/premarital-care/wife',
    name: '女方档案',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 197,
    type: 'others',
    key: '/premarital-care/husband',
    name: '男方档案',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 196,
    type: 'others',
    key: '/premarital-care/visit-wife',
    name: '女方婚前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 195,
    type: 'others',
    key: '/premarital-care/visit-husband',
    name: '男方婚前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 194,
    type: 'others',
    key: '/premarital-care/certification',
    name: '婚前医学证明',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 194,
    type: 'others',
    key: '/premarital-care/statistics',
    name: '婚检统计',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 179,
    type: 'others',
    key: '/gynecological-diseases',
    name: '妇女病普查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 178,
    type: 'others',
    key: '/gynecological-diseases/women',
    name: '档案管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 177,
    type: 'others',
    key: '/gynecological-diseases/examination',
    name: '妇女病普查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 176,
    type: 'others',
    key: '/gynecological-diseases/cervical-cancer-screen',
    name: '宫颈癌筛查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 175,
    type: 'others',
    key: '/gynecological-diseases/breast-cancer-screen',
    name: '乳腺癌筛查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 159,
    type: 'others',
    key: '/prenatal-visit',
    name: '产前检查',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 158,
    type: 'others',
    key: '/prenatal-visit/pregnancy',
    name: '孕册管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 157,
    type: 'others',
    key: '/prenatal-visit/initial',
    name: '首诊管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 156,
    type: 'others',
    key: '/prenatal-visit/return',
    name: '复诊管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 155,
    type: 'others',
    key: '/prenatal-visit/statistics',
    name: '统计报表',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 139,
    type: 'others',
    key: '/high-risk-management',
    name: '高危孕妇管理',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 138,
    type: 'others',
    key: '/high-risk-management/highrisk',
    name: '高危登记',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 137,
    type: 'others',
    key: '/high-risk-management/followup',
    name: '高危随访',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 137,
    type: 'others',
    key: '/high-risk-management/statistics',
    name: '统计报表',
    parentid: 0,
    active: null,
    isMenu: true,
  },
  {
    id: 119,
    type: 'others',
    key: '/prenatal-screening',
    active: null,
    isMenu: true,
  },
  {
    id: 99,
    type: 'others',
    key: '/prenatal-diagnosis',
    active: null,
    isMenu: true,
  },
];
