import { formatTimeToStandard } from '@/utils/format';
import { statusMapping } from '@/components/selects/NormalSelect';
import { keyBy, get } from 'lodash';

export const tableColumns = [
  {
    title: '姓名',
    dataIndex: 'admissionName',
    align: 'center',
    fixed: true,
    width: 100,
    render: (value: any, rowData: any) => get(rowData, 'admission.name'),
  },
  {
    title: '身份证号',
    dataIndex: 'idNO',
    align: 'center',
    fixed: true,
    width: 100,
    render: (value: any, rowData: any) => get(rowData, 'admission.idNO'),
  },
  {
    title: '孕周',
    dataIndex: 'gestationalWeek',
    align: 'center',
    fixed: true,
    width: 100,
    render: (value: any, rowData: any) => get(rowData, 'admission.gestationalWeek'),
  },
  {
    title: '孕产期',
    dataIndex: 'edd',
    align: 'center',
    width: 120,
    fixed: true,
    render: (value: any, rowData: any) => get(rowData, 'admission.edd'),
  },
  {
    title: '护理日期',
    dataIndex: 'nursedate',
    align: 'center',
    editable: true,
    inputType: 'single_date_picker',
    width: 200,
    render: (value: any) => formatTimeToStandard(value, 'YYYY-MM-DD'),
    sortType: 'date',
    filterType: 'date',
  },
  {
    title: '护理时间',
    dataIndex: 'nursetime',
    inputType: 'single_time_picker',
    inputProps: { format: 'HH:mm' },
    editable: true,
    render: (value: any) => formatTimeToStandard(value, 'HH:mm'),
    align: 'center',
    sortType: 'date',
    filterType: 'date',
  },
  {
    title: '体温',
    dataIndex: 'temperature',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '脉搏',
    dataIndex: 'pluse',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '心率',
    dataIndex: 'heartrate',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '呼吸',
    dataIndex: 'respiratory',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '意识',
    dataIndex: 'consciousness',
    editable: true,
    inputType: 'normal_select',
    inputProps: { type: 'hasOrNoMapping' },
    align: 'center',
    render: (value: any) => get(keyBy(statusMapping.hasOrNoMapping, 'value'), `${Boolean(value)}.title`),
  },
  {
    title: '血氧',
    dataIndex: 'bloodoxygen',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '收缩压',
    dataIndex: 'systolic',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '舒张压',
    dataIndex: 'diastolic',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    align: 'center',
  },
  {
    title: '特殊记录',
    dataIndex: 'note',
    editable: true,
    align: 'center',
  },
];
