import { formatTimeToStandard } from '@/utils/format';
import { statusMapping } from '@/components/selects/NormalSelect';
import { keyBy, get } from 'lodash';

export const tableColumns = [
  {
    title: '日期',
    dataIndex: 'visitDate',
    align: 'center',
    inputType: 'single_date_picker',
    fixed: true,
    width: 100,
    render: (value: any) => formatTimeToStandard(value, 'YYYY-MM-DD'),
  },
  {
    title: '孕周',
    dataIndex: 'gestationalWeek',
    align: 'center',
    width: 100,
  },
  {
    title: '体重',
    dataIndex: 'weight',
    align: 'center',
    width: 120,
    editable: true,
    inputProps: { min: 0 },
    render: (value: any, rowData: any) => get(rowData, 'physicalExam.weight'),
  },
  {
    title: '收缩压',
    dataIndex: 'physicalExam.diastolic',
    align: 'center',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    width: 200,
    render: (value: any, rowData: any) => get(rowData, 'physicalExam.diastolic'),
  },
  {
    title: '舒张压',
    dataIndex: 'physicalExam.systolic',
    align: 'center',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    width: 200,
    render: (value: any, rowData: any) => get(rowData, 'physicalExam.systolic'),
  },
  {
    title: '宫高',
    dataIndex: 'gynecologicalExam.fundalHeight',
    align: 'center',
    editable: true,
    inputType: 'input_number',
    inputProps: { min: 0 },
    width: 200,
    render: (value: any, rowData: any) => get(rowData, 'gynecologicalExam.fundalHeight'),
  },
  // {
  //   title: '下肢水肿',
  //   dataIndex: 'generalExam.edemaNote',
  //   editable: true,
  //   inputType: 'normal_select',
  //   inputProps: { type: 'hasOrNoMapping' },
  //   align: 'center',
  //   // render: (value: any) => get(keyBy(statusMapping.hasOrNoMapping, 'value'), `${Boolean(value)}.title`),
  // },
  {
    title: '下次复诊',
    dataIndex: 'appointmentDate',
    align: 'center',
    inputType: 'single_date_picker',
    editable: true,
    width: 100,
    render: (value: any) => formatTimeToStandard(value, 'YYYY-MM-DD'),
  },
  {
    title: '医生',
    dataIndex: 'doctor',
    align: 'center',
    width: 100,
  },

];
