// 分娩管理路由
export default {
  name: 'deliver-management',
  icon: 'ordered-list',
  path: '/deliver-management',
  routes: [
    {
      name: 'admission',
      icon: 'ordered-list',
      path: '/deliver-management/admission',
      component: './deliver-management/admission/list',
    },
    {
      name: 'admission-add',
      icon: 'ordered-list',
      path: '/deliver-management/admission/add',
      component: './deliver-management/admission/edit',
    },
    {
      name: 'admission-edit',
      icon: 'ordered-list',
      path: '/deliver-management/admission/edit',
      component: './deliver-management/admission/edit',
    },
    {
      name: 'labour-record',
      icon: 'ordered-list',
      path: '/deliver-management/labour-record',
      component: './deliver-management/labour-record/list',
    },
    {
      name: 'labour-record-add',
      icon: 'ordered-list',
      path: '/deliver-management/labour-record/add',
      component: './deliver-management/labour-record/edit',
    },
    {
      name: 'labour-record-edit',
      icon: 'ordered-list',
      path: '/deliver-management/labour-record/edit',
      component: './deliver-management/labour-record/edit',
    },
    {
      name: 'nursing-record',
      icon: 'ordered-list',
      path: '/deliver-management/nursing-record',
      component: './deliver-management/nursing-record/list',
    },
    {
      name: 'nursing-record-add',
      icon: 'ordered-list',
      path: '/deliver-management/nursing-record/add',
      component: './deliver-management/nursing-record/edit',
    },
    {
      name: 'nursing-record-edit',
      icon: 'ordered-list',
      path: '/deliver-management/nursing-record/edit',
      component: './deliver-management/nursing-record/edit',
    },
    {
      name: 'predelivery',
      icon: 'ordered-list',
      path: '/deliver-management/predelivery',
      component: './deliver-management/predelivery/list',
    },
    {
      name: 'predelivery-add',
      icon: 'ordered-list',
      path: '/deliver-management/predelivery/add',
      component: './deliver-management/predelivery/edit',
    },
    {
      name: 'predelivery-edit',
      icon: 'ordered-list',
      path: '/deliver-management/predelivery/edit',
      component: './deliver-management/predelivery/edit',
    },
    {
      name: 'caesarean-delivery',
      icon: 'ordered-list',
      path: '/deliver-management/caesarean-delivery',
      component: './deliver-management/caesarean-delivery/list',
    },
    {
      name: 'caesarean-delivery-add',
      icon: 'ordered-list',
      path: '/deliver-management/caesarean-delivery/add',
      component: './deliver-management/caesarean-delivery/edit',
    },
    {
      name: 'caesarean-delivery-edit',
      icon: 'ordered-list',
      path: '/deliver-management/caesarean-delivery/edit',
      component: './deliver-management/caesarean-delivery/edit',
    },
    {
      name: 'neonate-record',
      icon: 'ordered-list',
      path: '/deliver-management/neonate-record',
      component: './deliver-management/neonate-record/list',
    },
    {
      name: 'neonate-record-add',
      icon: 'ordered-list',
      path: '/deliver-management/neonate-record/add',
      component: './deliver-management/neonate-record/edit',
    },
    {
      name: 'neonate-record-edit',
      icon: 'ordered-list',
      path: '/deliver-management/neonate-record/edit',
      component: './deliver-management/neonate-record/edit',
    },
    {
      name: 'postpartum-visit',
      icon: 'ordered-list',
      path: '/deliver-management/postpartum-visit',
      component: './deliver-management/postpartum-visit/list',
    },
    {
      name: 'postpartum-visit-add',
      icon: 'ordered-list',
      path: '/deliver-management/postpartum-visit/add',
      component: './deliver-management/postpartum-visit/edit',
    },
    {
      name: 'postpartum-visit-edit',
      icon: 'ordered-list',
      path: '/deliver-management/postpartum-visit/edit',
      component: './deliver-management/postpartum-visit/edit',
    },
  ],
};
