const data = {
  "ivisitId": "25223",
  "userid": "25223",
  "usermcno": "05781816",
  "gravidaInfo": {
  "usercuzh": "2020-04-28 11:07:12",
  "chanjno": "2005-008",
  "userbirth": "2020-03-11",
  "userage": "31",
  "usernation": "中",
  "userroots": "中国",
  "userpeople": "苗族",
  "useroccupation": "{\"label\":\"国家公务员\",\"value\":\"国家公务员\"}",
  "usermobile": "18688444659",
  "phone": "789",
  "useridtype": "{\"label\":\"0\",\"value\":\"身份证\"}",
  "useridno": "420222198910010181",
  "userconstant": "广东省,广州市,荔湾区,车站街道",
  "userconstantd": "888899",
  "useraddress": "内蒙古自治区,巴彦淖尔市,杭锦后旗,蛮会镇",
  "useraddressd": "76677",
  "add_FIELD_coming_this_city": "",
  "add_FIELD_zhunsz": "123",
  "add_FIELD_readdress": "1223"
  },
  "husbandInfo": {
  "userhname": "sadf士大夫",
  "userhage": "24",
  "userhnation": "",
  "userhroots": "{\"label\":\"浙江\",\"value\":\"浙江\"}",
  "userhpeople": "汉族",
  "userhoccupation": "{\"label\":\"自由职业者\",\"value\":\"自由职业者\"}",
  "userhmobile": "",
  "userhidno": "789",
  "userhconstant": "",
  "userhyanL": "",
  "userhjib": "无",
  "userhmcno": "112",
  "add_FIELD_husband_drink_type": "{\"label\":\"无\",\"value\":\"无\"}",
  "add_FIELD_husband_userroots": "",
  "add_FIELD_husband_useridtype": "{\"label\":\"身份证\",\"value\":\"身份证\"}",
  "add_FIELD_husband_drink_data": "{\"0\":{\"label\":\"无\",\"value\":\"无\"},\"1\":\"\"}",
  "add_FIELD_h_userconstantd": "",
  "add_FIELD_husband_smoking": "",
  "add_FIELD_husband_drink": "",
  "add_FIELD_h_coming_this_city": "2020-03-06",
  "add_FIELD_h_userconstant": "天津市,市辖区,和平区,劝业场街道"
  },
  "pregnantInfo": {
  "gesmoc": "2020-03-11",
  "gesexpect": "2020-12-16",
  "gesexpectrv": "2020-12-16",
  "ckyibzhzh": "",
  "ckyibzhzhtd": "",
  "dopupt": "",
  "pupttm": "NaN+NaN",
  "ckzdate": "",
  "ckztingj": "",
  "fetalMovement": "",
  "ckzweek": "12+3",
  "ckzcrl": "19",
  "ckzbpd": "123",
  "add_FIELD_shouyun": "",
  "add_FIELD_shouyunNote": "",
  "add_FIELD_gesmoc_unknown": "[]",
  "add_FIELD_ckyibzhzh_ty_desc": "",
  "add_FIELD_ckyibzhzh_tt_desc": "",
  "add_FIELD_ckyibzhzh_ot_desc": "",
  "add_FIELD_ckyibzhzh_fz_desc": "",
  "add_FIELD_ckyibzhzh_bm_desc": "",
  "add_FIELD_ckyibzhzh_bdzd_desc": "",
  "add_FIELD_ckyibzhzh_xm_desc": "",
  "add_FIELD_ckyibzhzh_yt_desc": "",
  "add_FIELD_ckyibzhzh_dt_desc": "",
  "add_FIELD_ckyibzhzh_cj_desc": "",
  "add_FIELD_ckyibzhzh_lx_desc": "",
  "add_FIELD_ckyibzhzh_other_desc": ""
  },
  "hisInfo": {
  "bsjibing": "",
  "bsshoushu": "",
  "bsshoushuother": "",
  "bsguomin": "[{\"label\":\"药物\",\"value\":\"1\"}]",
  "hobtabp": "[{\"label\":\"有\",\"value\":{\"input1\":\"q\",\"input0\":\"1\"}}]",
  "add_FIELD_bsjibing_gxy_desc": "",
  "add_FIELD_bsjibing_tnb_desc": "",
  "add_FIELD_bsjibing_xzb_desc": "",
  "add_FIELD_bsjibing_szjb_desc": "",
  "add_FIELD_bsjibing_gzjb_desc": "",
  "add_FIELD_bsjibing_jk_desc": "",
  "add_FIELD_bsjibing_g6pd_desc": "",
  "add_FIELD_bsjibing_dzhpx_desc": "",
  "add_FIELD_bsjibing_fjh_desc": "",
  "add_FIELD_bsjibing_px_desc": "",
  "add_FIELD_bsjibing_sy_desc": "",
  "add_FIELD_bsjibing_gy_desc": "",
  "add_FIELD_bsjibing_fs_desc": "",
  "add_FIELD_bsjibing_db_desc": "",
  "add_FIELD_bsjibing_other_desc": "",
  "add_FIELD_bsguomin_swgm": "",
  "add_FIELD_bsguomin_other": "",
  "add_FIELD_hobtabp_hxb_time": "",
  "add_FIELD_hobtabp_hxb_dept": "",
  "add_FIELD_hobtabp_hxb_resource": "",
  "add_FIELD_hobtabp_xxb_time": "",
  "add_FIELD_hobtabp_xxb_dept": "",
  "add_FIELD_hobtabp_xxb_resource": "",
  "add_FIELD_hobtabp_bxb_time": "",
  "add_FIELD_hobtabp_bxb_dept": "",
  "add_FIELD_hobtabp_bxb_resource": "",
  "add_FIELD_hobtabp_xj_time": "",
  "add_FIELD_hobtabp_xj_dept": "",
  "add_FIELD_hobtabp_xj_resource": "",
  "add_FIELD_hobtabp_qx_time": "",
  "add_FIELD_hobtabp_qx_dept": "",
  "add_FIELD_hobtabp_qx_resource": "",
  "add_FIELD_hobtabp_bdb_time": "",
  "add_FIELD_hobtabp_bdb_dept": "",
  "add_FIELD_hobtabp_bdb_resource": "",
  "add_FIELD_hobtabp_oth": "",
  "add_FIELD_mb_sxs": "",
  "add_FIELD_symptom": "贝阿恩和团结",
  "add_FIELD_has_operation_history": "[{\"label\":\"有\",\"value\":\"1\"}]",
  "add_FIELD_xinzangbing": "[{\"label\":\"有\",\"value\":\"1\"}]",
  "add_FIELD_gaoxueya": "[{\"label\":\"有\",\"value\":\"1\"}]",
  "add_FIELD_tangniaobing": "[{\"label\":\"有\",\"value\":\"1\"}]",
  "add_FIELD_qitabingshi": "[{\"label\":\"有\",\"value\":\"1\"}]"
  },
  "operationHistory": {
  "userid": "25223",
  "operationHistorys": [
  {
  "parseAddFieldLocations": null,
  "saveInitialData": false,
  "id": 129,
  "userid": 25223,
  "name": "乳腺纤维瘤切除术",
  "date": "2016",
  "hospital": null,
  "postoperativePathology": "良性",
  "addField": "",
  "writeOperationType": null
  }
  ]
  },
  "menstruationMarriage": {
  "yjcuch": "{\"label\":\"13\",\"value\":\"13\"}",
  "yjzhouq": "30",
  "yjchix": "12",
  "yjjingl": "",
  "yjtongj": "[{\"label\":\"偶尔\",\"value\":\"\"},{\"label\":\"有\",\"value\":\"\"}]",
  "maritalHistory": "[{\"label\":\"已婚\",\"value\":\"\"}]",
  "userjiehn": "",
  "userjinqjh": "[]",
  "historyOfInfertility": "",
  "add_FIELD_historyOfInfertility_slg_time": "",
  "add_FIELD_historyOfInfertility_slg_therapy": "",
  "add_FIELD_historyOfInfertility_jz_time": "",
  "add_FIELD_historyOfInfertility_jz_therapy": "",
  "add_FIELD_historyOfInfertility_lc_time": "",
  "add_FIELD_historyOfInfertility_lc_therapy": "",
  "add_FIELD_historyOfInfertility_yy_time": "",
  "add_FIELD_historyOfInfertility_yy_therapy": "",
  "add_FIELD_historyOfInfertility_other": ""
  },
  "biography": {
  "bsguomin": "[{\"label\":\"药物\",\"value\":\"1\"}]",
  "userhistory": "",
  "mzxuan": "高血压,遗传病",
  "mzxuanother": "",
  "add_FIELD_bsguomin_swgm": "",
  "add_FIELD_bsguomin_other": "",
  "add_FIELD_userhistory_Smoke": "",
  "add_FIELD_userhistory_drink": "",
  "add_FIELD_userhistory_ydyh": "",
  "add_FIELD_userhistory_ywmc": "",
  "add_FIELD_userhistory_jl": "",
  "add_FIELD_userhistory_pl": "",
  "add_FIELD_userhistory_yf": "",
  "add_FIELD_mzxuan6": "",
  "add_FIELD_mzxuan61": "",
  "add_FIELD_userhistory_fyys": "",
  "add_FIELD_grxiyan": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_gryinjiu": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_gryouhai": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_grfangshe": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_grqita": "[]",
  "add_FIELD_jzgaoxueya": "[{\"label\":\"有\",\"value\":\"\"}]",
  "add_FIELD_jztangniaobing": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_jzjixing": "[{\"label\":\"无\",\"value\":\"\"}]",
  "add_FIELD_jzyichuanbing": "[{\"label\":\"有\",\"value\":\"\"}]",
  "add_FIELD_jzqita": "[]"
  },
  "gestation": {
  "userid": 25223,
  "preghiss": [
  {
  "id": 48598,
  "userid": 25223,
  "pregnum": "1",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "",
  "reng": "true",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2007",
  "removalUterus": null,
  "births": 0
  },
  {
  "id": 48600,
  "userid": 25223,
  "pregnum": "2",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "true",
  "reng": "true",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "true",
  "zaoch": "true",
  "sich": "",
  "shunch": "true",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "1",
  "xingb": "男",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "1111",
  "zuych": "true",
  "yinch": "true",
  "chuxue": "true",
  "chanrure": "true",
  "xinseother": "",
  "fenm": "",
  "child": "健在",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "剖宫产",
  "deathTime": "1",
  "deathCause": "1",
  "sequela": "1",
  "subsistence": "",
  "hospital": "广医一院",
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2007-01",
  "removalUterus": "true",
  "births": 1
  },
  {
  "id": 48602,
  "userid": 25223,
  "pregnum": "2",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "",
  "reng": "",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2007-01",
  "removalUterus": null,
  "births": 1
  },
  {
  "id": 48596,
  "userid": 25223,
  "pregnum": "3",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "true",
  "reng": "",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2008",
  "removalUterus": null,
  "births": 0
  },
  {
  "id": 48594,
  "userid": 25223,
  "pregnum": "4",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "true",
  "reng": "true",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "true",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2009-10",
  "removalUterus": "true",
  "births": 1
  },
  {
  "id": 48573,
  "userid": 25223,
  "pregnum": "5",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "",
  "reng": "",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "死亡",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2017",
  "removalUterus": null,
  "births": 0
  },
  {
  "id": 48471,
  "userid": 25223,
  "pregnum": "6",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "false",
  "reng": "false",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "false",
  "zaoch": "",
  "sich": "",
  "shunch": "false",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "男",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "4256",
  "zuych": "false",
  "yinch": "",
  "chuxue": "false",
  "chanrure": "false",
  "xinseother": "",
  "fenm": "",
  "child": "未知",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": "中山一院",
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "2020-11",
  "removalUterus": "false",
  "births": 0
  },
  {
  "id": 48627,
  "userid": 25223,
  "pregnum": "7",
  "pregdatey": "",
  "pregdatem": "",
  "zir": "",
  "reng": "",
  "yaol": "",
  "putt": "",
  "yiwrsh": "",
  "sit": "",
  "zaoch": "",
  "sich": "",
  "shunch": "",
  "pougch": "",
  "xiych": "",
  "qianch": "",
  "tunzhch": "",
  "tizh": "",
  "xingb": "",
  "jix": "",
  "siw": "",
  "jianz": "",
  "bingfzh": "",
  "zuych": "",
  "yinch": "",
  "chuxue": "",
  "chanrure": "",
  "xinseother": "",
  "fenm": "",
  "child": "",
  "abortion": "",
  "unhealth": "",
  "others": "",
  "isdeleted": "",
  "gesweek": null,
  "shouShuChanType": "",
  "deathTime": "",
  "deathCause": "",
  "sequela": "",
  "subsistence": "",
  "hospital": null,
  "addField": null,
  "xsrqk": "",
  "addFlag": null,
  "datagridYearMonth": "本孕",
  "removalUterus": null,
  "births": 0
  }
  ]
  },
  "lis": {
  "ckxuex": "{\"label\":\"A\",\"value\":\"A\"}",
  "ckrh": "{\"label\":\"RH(+)\",\"value\":\"RH(+)\"}",
  "husbandCkxuex": "{\"label\":\"A\",\"value\":\"A\"}",
  "husbandRh": "{\"label\":\"RH(+)\",\"value\":\"RH(+)\"}",
  "hbsAg": "[{\"label\":\"未查\",\"value\":\"\"}]",
  "hcvAb": "[{\"label\":\"阳性\",\"value\":\"1\"}]",
  "rpr": "[{\"label\":\"阳性\",\"value\":\"\"}]",
  "ogtt": "[{\"label\":\"GDM\",\"value\":{\"input2\":\"15\",\"input1\":\"10\",\"input0\":\"10\"}}]",
  "thalassemia": "[{\"label\":\"正常\",\"value\":\"\"}]",
  "husbandThalassemia": "[{\"label\":\"未查\",\"value\":\"\"}]",
  "aids": "[{\"label\":\"阴性\",\"value\":\"\"}]",
  "ckfzother": "测试测试测试测试测试测试测试测试测试测试测试测试测试测试",
  "add_FIELD_hbsAg_DNA": "",
  "add_FIELD_hbsAg_ALT": "1",
  "add_FIELD_hbsAg_AST": "2",
  "add_FIELD_hcvAb_RNA": "[{\"label\":\"阳性\",\"value\":\"\"}]",
  "add_FIELD_rpr_dd_tppa": "",
  "add_FIELD_rpr_dd_trust": "",
  "add_FIELD_ogtt_gdm_empty": "10",
  "add_FIELD_ogtt_gdm_1h": "10",
  "add_FIELD_ogtt_gdm_2h": "15",
  "add_FIELD_ndb": "[{\"label\":\"阳性\",\"value\":\"\"}]",
  "add_FIELD_lis_hb": "56/68",
  "add_FIELD_lis_hb_unusual": "",
  "add_FIELD_lis_mcv": "34",
  "add_FIELD_lis_mcv_unusual": "",
  "add_FIELD_lis_plt": "56",
  "add_FIELD_lis_plt_unusual": "",
  "add_FIELD_GBS": "[{\"label\":\"未查\",\"value\":\"\"}]",
  "add_FIELD_TSH": "39",
  "add_FIELD_TSH_unusual": "↑",
  "add_FIELD_free_t3": "56",
  "add_FIELD_free_t3_unusual": "↓",
  "add_FIELD_free_t4": "70",
  "add_FIELD_free_t4_unusual": "",
  "add_FIELD_early_downs_syndrome": "[{\"label\":\"低风险\",\"value\":\"\"}]",
  "add_FIELD_mk_downs_syndrome": "[{\"label\":\"高风险\",\"value\":\"\"}]",
  "add_FIELD_nipt": "[{\"label\":\"高风险\",\"value\":\"\"}]",
  "add_FIELD_outpatient": "[{\"label\":\"低风险\",\"value\":\"\"}]",
  "add_FIELD_hbsAg_other": "",
  "add_FIELD_rpr_other": "",
  "add_FIELD_thalassemia_a_other": "",
  "add_FIELD_thalassemia_b_other": "",
  "add_FIELD_thalassemia_other": "",
  "add_FIELD_husbandThalassemia_a_other": "",
  "add_FIELD_husbandThalassemia_b_other": "",
  "add_FIELD_husbandThalassemia_other": "",
  "add_FIELD_ndb_other": ""
  },
  "checkUp": {
  "cktizh": "45",
  "ckshrinkpressure": "145",
  "ckdiastolicpressure": "238",
  "firstBpSystolic": "145",
  "firstBpDiastolic": "238",
  "secondBpSystolic": "46",
  "secondBpDiastolic": "89",
  "threeBpSystolic": "45",
  "threeBpDiastolic": null,
  "ckcurtizh": "57",
  "cksheng": "162.0",
  "ckbmi": "17.1",
  "ckpifu": "[{\"label\":\"正常\",\"value\":\"\"}]",
  "ckjiazhx": "[{\"label\":\"其他\",\"value\":\"\"}]",
  "vascularMurmur": "[{\"label\":\"�?\",\"value\":\"\"}]",
  "vascularMurmurOther": "[{\"label\":\"�?\",\"value\":\"\"},{\"label\":\"无\",\"value\":\"\"}]",
  "ckrut": "[{\"label\":\"其他\",\"value\":\"\"}]",
  "breathSounds": "[{\"label\":\"�?\",\"value\":\"\"},{\"label\":\"清\",\"value\":\"\"}]",
  "breathSoundsOther": "[{\"label\":\"�?\",\"value\":\"\"},{\"label\":\"无\",\"value\":\"\"}]",
  "heart": "[{\"label\":\"齐\",\"value\":\"\"}]",
  "cardiac": "680",
  "murmurs": "[{\"label\":\"�?\",\"value\":\"\"},{\"label\":\"无\",\"value\":\"\"}]",
  "ckganz": "[{\"label\":\"未触�?\",\"value\":\"\"},{\"label\":\"未触及\",\"value\":\"\"}]",
  "ckpiz": "[{\"label\":\"可触�?\",\"value\":\"\"},{\"label\":\"可触及\",\"value\":\"\"}]",
  "ckshenz": "[{\"label\":\"�?\",\"value\":\"\"},{\"label\":\"无\",\"value\":\"\"}]",
  "ckjizh": "[{\"label\":\"正常\",\"value\":\"\"}]",
  "ckfuzh": "[{\"label\":\"+++\",\"value\":\"\"}]",
  "nervousReflex": "[{\"label\":\"存在\",\"value\":\"\"}]",
  "add_FIELD_pulse": "68",
  "add_FIELD_ckpifu_pxcx": "",
  "add_FIELD_ckpifu_other": "",
  "add_FIELD_ckjiazhx_yc": "",
  "add_FIELD_breathSounds_yc": "",
  "add_FIELD_cardiac_bq": "",
  "add_FIELD_murmurs_y": "",
  "add_FIELD_ckjizh_jx": "",
  "add_FIELD_checkup_other": "3635636",
  "add_FIELD_headFeatures": "[{\"label\":\"其他\",\"value\":\"\"}]"
  },
  "specialityCheckUp": {
  "ckwaiy": "{\"label\":\"未见异常\",\"value\":\"未见异常\"}",
  "ckyind": "{\"label\":\"未见异常\",\"value\":\"未见异常\"}",
  "ckgongj": "{\"label\":\"未见异常\",\"value\":\"未见异常\"}",
  "ckgongt": "{\"label\":\"未见异常\",\"value\":\"未见异常\"}",
  "ckfuj": "{\"label\":\"未见异常\",\"value\":\"未见异常\"}",
  "ckgongg": "123",
  "ckfuw": "",
  "cktaix": "",
  "ckxianl": "",
  "cktaiw": "",
  "ckqiaj1": "",
  "ckqiaj2": "",
  "ckdichi": "",
  "ckzugu": "",
  "add_FIELD_gpwcl": "",
  "add_FIELD_gynecological_examination": "[]",
  "add_FIELD_ckjc": "[{\"xl\":{\"label\":\"-\",\"value\":\"-\"},\"tx\":\"10\"},{}]"
  },
  "diagnosis": {
  "zhendyc": "",
  "zhendchc": "",
  "zhendgnrs": "",
  "diagnosisHandle": "B 超； 胎监； 爱上对方发斯蒂芬入院；asdf",
  "nextRvisitWeek": "",
  "xiacsfdate": "2020-05-11",
  "xiacsftype": "{\"0\":\"�?\",\"1\":\"�?\",\"2\":\"�?\",\"3\":\"�?\",\"label\":\"高危门诊\",\"describe\":\"�?\",\"value\":1}",
  "xiacsfdatearea": "{\"0\":\"上\",\"1\":\"午\",\"label\":\"上午\",\"describe\":\"上\",\"value\":\"上午\"}",
  "yunc": "7",
  "chanc": "2",
  "tuserweek": "",
  "add_FIELD_ivisit_doctor": "\"null\"",
  "add_FIELD_first_ivisit_doctor": "\"null\"",
  "add_FIELD_first_clinical_doctor": "asdf",
  "add_FIELD_first_save_ivisit_time": "2020-04-11",
  "add_FIELD_tuserweek": "8+5"
  },
  "diagnosisList": [
  {
  "id": 14913,
  "data": "妊娠期糖尿病",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": null,
  "remark": ""
  },
  {
  "id": 14918,
  "data": "双胎妊娠",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": null,
  "remark": ""
  },
  {
  "id": 14917,
  "data": "双胎",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": "1",
  "remark": ""
  },
  {
  "id": 14919,
  "data": "特指多胎妊娠",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": null,
  "remark": ""
  },
  {
  "id": 14914,
  "data": "妊娠高血压",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": "1",
  "remark": ""
  },
  {
  "id": 14916,
  "data": "丙型肝炎病毒",
  "highriskmark": "",
  "relatedformtype": "",
  "doctor": "",
  "createdate": "2020-05-09",
  "isdeleted": "1",
  "remark": ""
  }
  ],
  "temps": [
  {
  "id": 1,
  "pid": 0,
  "content": "13周常用模板",
  "doctorid": null
  },
  {
  "id": 2,
  "pid": 1,
  "content": "产检一套",
  "doctorid": null
  },
  {
  "id": 3,
  "pid": 1,
  "content": "查NT",
  "doctorid": null
  },
  {
  "id": 5,
  "pid": 1,
  "content": "早期唐筛",
  "doctorid": null
  },
  {
  "id": 6,
  "pid": 1,
  "content": "NIPT",
  "doctorid": null
  },
  {
  "id": 7,
  "pid": 1,
  "content": "产前诊断",
  "doctorid": null
  },
  {
  "id": 9,
  "pid": 0,
  "content": "16-20周常用模板",
  "doctorid": null
  },
  {
  "id": 10,
  "pid": 0,
  "content": "20-24周常用模板",
  "doctorid": null
  },
  {
  "id": 11,
  "pid": 0,
  "content": "28周常用模板",
  "doctorid": null
  },
  {
  "id": 12,
  "pid": 0,
  "content": "37周常用模板",
  "doctorid": null
  },
  {
  "id": 13,
  "pid": 9,
  "content": "中期唐筛",
  "doctorid": null
  },
  {
  "id": 15,
  "pid": 9,
  "content": "排畸B超",
  "doctorid": null
  },
  {
  "id": 16,
  "pid": 10,
  "content": "查OGTT、血脂、糖化血红蛋白",
  "doctorid": null
  },
  {
  "id": 17,
  "pid": 11,
  "content": "查血尿常规、生化、肝功、肝代谢",
  "doctorid": null
  },
  {
  "id": 18,
  "pid": 11,
  "content": "B超",
  "doctorid": null
  },
  {
  "id": 19,
  "pid": 12,
  "content": "查血尿常规、出凝血、生化、肝功、肝代谢",
  "doctorid": null
  },
  {
  "id": 20,
  "pid": 11,
  "content": "数胎动",
  "doctorid": null
  },
  {
  "id": 21,
  "pid": 12,
  "content": "估重B超",
  "doctorid": null
  },
  {
  "id": 22,
  "pid": 12,
  "content": "若有腹痛、阴道流水或胎动减少，请立即看急诊",
  "doctorid": null
  },
  {
  "id": 23,
  "pid": 0,
  "content": "其他常用模板",
  "doctorid": null
  },
  {
  "id": 24,
  "pid": 23,
  "content": "控制体重",
  "doctorid": null
  },
  {
  "id": 25,
  "pid": 23,
  "content": "数胎动",
  "doctorid": null
  },
  {
  "id": 26,
  "pid": 23,
  "content": "加强营养",
  "doctorid": null
  },
  {
  "id": 27,
  "pid": 23,
  "content": "注意腹痛和出血情况，不适急诊",
  "doctorid": null
  },
  {
  "id": 28,
  "pid": 23,
  "content": "若有腹痛、阴道流水或胎动减少，请立即看急诊",
  "doctorid": null
  },
  {
  "id": 29,
  "pid": 23,
  "content": "转糖尿病日间门诊",
  "doctorid": null
  },
  {
  "id": 31,
  "pid": 3,
  "content": "new node1",
  "doctorid": null
  },
  {
  "id": 32,
  "pid": 5,
  "content": "new node1",
  "doctorid": null
  },
  {
  "id": 33,
  "pid": 32,
  "content": "new node2",
  "doctorid": null
  }
  ],
  "physicalExamBO": {
  "id": null,
  "ids": null,
  "mcno": "05781816",
  "userName": null,
  "height": null,
  "weight": null,
  "systolic": null,
  "diastolic": null,
  "firstBp": null,
  "firstBpSystolic": null,
  "firstBpDiastolic": null,
  "secondBp": null,
  "secondBpSystolic": null,
  "secondBpDiastolic": null,
  "threeBp": null,
  "threeBpSystolic": null,
  "threeBpDiastolic": null,
  "heartrate": null,
  "msdate": "2020-05-11",
  "createTime": null,
  "firstId": null,
  "secondId": null,
  "threeId": null
  }
}

export default data;
