const data = {
  "id": 55298693.35310623,
  "visitType": "sint lab",
  "serialNo": null,
  "visitDate": "dolor reprehenderit nostrud",
  "gestationalWeek": null,
  "appointmentType": null,
  "appointmentDate": null,
  "appointmentPeriod": null,
  "diagnosis": null,
  "diagnosisCode": null,
  "physicalExam": {
    "id": -85389347.41887009,
    "height": null,
    "weight": -79278393.0522714,
    "systolic": null,
    "diastolic": null,
    "pulse": null,
    "temperature": null
  },
  "generalExam": {
    "heart": '',
    "heartrate": '',
    "heartrhythm": '',
    "murmurs": '',
    "respiratory": '',
    "rales": '',
    "lung": '',
    "liver": '',
    "thyroid": '',
    "breast": '',
    "nipple": '',
    "spleen": '',
    "stomach": '',
    "jaundice": '',
    "skin": '',
    "edema": '',
    "thorax": '',
    "spine": '',
    "physiologicalreflection": '',
    "pathologicalreflection": '',
    "mentalstate": '',
    "face": '',
    "posture": '',
    "intelligence": '',
    "limbs": '',
  },
  "gynecologicalExam": {
    "id": 64842587.654999435,
    "fundalHeight": null,
    "waistHip": null,
    "engagement": null,
    "breast": null,
    "breastNote": null,
    "nipple": null,
    "nippleNote": null,
    "pubes": null,
    "examType": null,
    "vulva": null,
    "uterus": null,
    "vagina": null,
    "cervix": null,
    "adnexa": null
  },
  "pelvicExam": null,
  "labExams": null,
  "diagnoses": null,
  "imageExams": null,
  "serviceorders": null,
  "pregnancy": {
    "id": -26746769.146185607,
    "outpatientNO": "incididunt veniam eu qui",
    "inpatientNO": null,
    "checkupNO": null,
    "insuranceType": null,
    "name": "sit laboris",
    "age": 15318307.276431262,
    "gender": null,
    "dob": "aliqua",
    "idType": 81667725.29888737,
    "idNO": "veniam culpa do",
    "nationality": "exercitation",
    "nativeplace": "sit deserunt commodo aute",
    "ethnic": "consectetur ipsum ut qui dolore",
    "telephone": "aute amet ipsum incididunt",
    "maritalStatus": -99099964.93727027,
    "nearRelation": true,
    "maritalYears": -3339957.2831966877,
    "education": null,
    "occupation": "cupidatat veniam dolor id quis",
    "workplace": null,
    "workPhone": null,
    "occupationDetail": null,
    "familyIncome": null,
    "residenceAddress": "officia",
    "permanentResidenceAddress": "in",
    "postpartumAddress": "incididunt in consequat et sed",
    "partnerName": "pariatur commodo consequat reprehenderit",
    "partnerGender": "irure amet",
    "partnerDob": "minim eu ",
    "partnerIdType": -18217286.60040316,
    "partnerIdNO": "cillum",
    "partnerNationality": "esse",
    "partnerNativeplace": "dolor",
    "partnerEthnic": "do cillum ut aliqua",
    "partnerTelephone": "velit sed consecte",
    "partnerOccupation": "nostrud sunt cillum",
    "partnerWorkplace": null,
    "partnerOccupationDetail": null,
    "lmp": "2017-08-08",
    "edd": "2017-08-09",
    "sureEdd": "2017-08-15",
    "gravidity": -25089507.15557821,
    "parity": -16049374.628765017,
    "gestationalWeek": null,
    "createDate": null,
    "modifyDate": null,
    "validateDate": null,
    "note": null,
    "recordsrc": null,
    "recordstate": null,
    "referral": null,
    "familyHistory": {
      "id": -63134168.15685651,
      "hypertension": false,
      "hypertensionNote": null,
      "hepaticDisease": null,
      "hepaticDiseaseNote": null,
      "epilepsy": null,
      "epilepsyNote": null,
      "cardiacDisease": null,
      "cardiacDiseaseNote": null,
      "endocrineDisease": null,
      "endocrineDiseaseNote": null,
      "thyroidDisease": null,
      "thyroidDiseaseNote": null,
      "hematopathy": null,
      "hematopathyNote": null,
      "mentalDisease": null,
      "mentalDiseaseNote": null,
      "diabetes": null,
      "diabetesNote": null,
      "birthdefects": null,
      "birthdefectsNote": null,
      "other": null,
      "otherNote": null
    },
    "procedureHistory": null,
    "diseaseHistory": {
      "id": -64302585.48106478,
      "hypertension": true,
      "hypertensionNote": "ex magna velit minim dolore",
      "nephropathy": null,
      "nephropathyNote": null,
      "respiratoryDisease": null,
      "respiratoryDiseaseNote": null,
      "gastroDisease": null,
      "gastroDiseaseNote": null,
      "hepaticDisease": null,
      "hepaticDiseaseNote": null,
      "epilepsy": null,
      "epilepsyNote": null,
      "cardiacDisease": true,
      "cardiacDiseaseNote": "veniam ex mollit Lo",
      "endocrineDisease": null,
      "endocrineDiseaseNote": null,
      "thyroidDisease": null,
      "thyroidDiseaseNote": null,
      "hematopathy": null,
      "hematopathyNote": null,
      "mentalDisease": null,
      "mentalDiseaseNote": null,
      "diabetes": true,
      "diabetesNote": "magna cillum consectetur enim elit",
      "other": null,
      "otherNote": null
    },
    "allergyHistory": null,
    "partnerProfile": {
      "id": 76149910.7877118,
      "outpatientNO": "dolor officia",
      "smoke": false,
      "smokeNote": "quis reprehenderit aliquip tempor cupidatat",
      "alcohol": false,
      "alcoholNote": "minim",
      "aBO": null,
      "rH": null,
      "disease": "occaecat"
    },
    "personalProfile": {
      "id": -23852020.88400939,
      "preheight": null,
      "preweight": 28647763.56167233,
      "bmi": null,
      "smoke": true,
      "smokeNote": "ad est ullamco pariatur",
      "alcohol": true,
      "alcoholNote": "et non",
      "aBO": null,
      "rH": null,
      "radioactivity": true,
      "radioactivityNote": "aliquip pariatur exercitation eu mollit",
      "medicine": true,
      "medicineNote": null,
      "hazardoussubstances": null,
      "hazardoussubstancesNote": null,
      "other": null,
      "otherNote": null
    },
    "menstrualHistory": {
      "id": -54550690.332632,
      "menarche": "commodo o",
      "menstrualCycle": "qui laborum",
      "menstrualPeriod": "eiusmod tempor consequat",
      "menstrualVolume": "cillum",
      "dysmenorrhea": false,
      "dysmenorrheaNote": null
    },
    "transfusionHistory": null,
    "pregnancyHistories": [
      {
        "id": -68372448.57682885,
        "gravidityindex": 8995023.449587464,
        "year": "2007",
        "month": "velit in adipisicing veniam",
        "term": null,
        "vaginalDelivery": null,
        "cesareanSection": null,
        "forceps": null,
        "vacuumAssisted": null,
        "breechMidwifery": null,
        "puerperalFever": null,
        "hemorrhage": null,
        "abortion": null,
        "abortionNote": null,
        "medicalAbortion": null,
        "surgicalAbortion": null,
        "naturalAbortion": null,
        "currettage": null,
        "stillbirth": null,
        "fetusdeath": null,
        "inducedLabor": null,
        "ectopicPregnancy": null,
        "hydatidMole": null,
        "multiple": null,
        "fetalcount": null,
        "hospital": null,
        "complication": null,
        "complicationNote": null,
        "exceptionalcase": null,
        "note": null,
        "pregnancy": {
          "id": 29865310.00010632,
          "outpatientNO": "laborum in",
          "inpatientNO": null,
          "checkupNO": null,
          "insuranceType": null,
          "name": "elit cillum Ut",
          "age": -57801074.34911481,
          "gender": null,
          "dob": "proident officia",
          "idType": -80262190.81310022,
          "idNO": "Excepteur qui exercitation",
          "nationality": "labore velit voluptate",
          "nativeplace": "cupidatat incididunt proident ipsum",
          "ethnic": "dolor aute ",
          "telephone": "labore",
          "maritalStatus": 69633921.10302132,
          "nearRelation": true,
          "maritalYears": 47565960.74302629,
          "education": null,
          "occupation": "incididunt",
          "workplace": null,
          "workPhone": null,
          "occupationDetail": null,
          "familyIncome": null,
          "residenceAddress": "occ",
          "permanentResidenceAddress": "occaecat in",
          "postpartumAddress": "consequat",
          "partnerName": "id occaecat esse",
          "partnerGender": "deserunt",
          "partnerDob": "ad aute dolor ipsum",
          "partnerIdType": 33482419.123209447,
          "partnerIdNO": "Ut",
          "partnerNationality": "culpa aliquip",
          "partnerNativeplace": "fugiat",
          "partnerEthnic": "veniam Lorem com",
          "partnerTelephone": "labore",
          "partnerOccupation": "est enim sunt ipsum",
          "partnerWorkplace": null,
          "partnerOccupationDetail": null,
          "lmp": "sed amet",
          "edd": "Lorem pariatur ",
          "sureEdd": "eu",
          "gravidity": 80553464.60277164,
          "parity": -51248335.4279067,
          "gestationalWeek": null,
          "createDate": null,
          "modifyDate": null,
          "validateDate": null,
          "note": null,
          "recordsrc": null,
          "recordstate": null,
          "referral": null,
          "familyHistory": {
            "id": -88175934.24043983,
            "hypertension": false,
            "hypertensionNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": null,
            "cardiacDiseaseNote": null,
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": null,
            "diabetesNote": null,
            "birthdefects": null,
            "birthdefectsNote": null,
            "other": null,
            "otherNote": null
          },
          "procedureHistory": null,
          "diseaseHistory": {
            "id": -24248929.782669663,
            "hypertension": true,
            "hypertensionNote": "ipsum deserunt nostrud ut",
            "nephropathy": null,
            "nephropathyNote": null,
            "respiratoryDisease": null,
            "respiratoryDiseaseNote": null,
            "gastroDisease": null,
            "gastroDiseaseNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": false,
            "cardiacDiseaseNote": "adipisicing irure fugiat enim consequat",
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": false,
            "diabetesNote": "pariat",
            "other": null,
            "otherNote": null
          },
          "allergyHistory": null,
          "partnerProfile": {
            "id": -82105316.21088877,
            "outpatientNO": "quis",
            "smoke": false,
            "smokeNote": "ipsum enim dolor eiusmod",
            "alcohol": false,
            "alcoholNote": "ex consequat",
            "aBO": null,
            "rH": null,
            "disease": ""
          },
          "personalProfile": {
            "id": 9150475.388947219,
            "preheight": null,
            "preweight": 87191805.76028931,
            "bmi": null,
            "smoke": false,
            "smokeNote": "esse",
            "alcohol": false,
            "alcoholNote": "eu ad anim in",
            "aBO": null,
            "rH": null,
            "radioactivity": true,
            "radioactivityNote": "Excepteur velit anim dolor",
            "medicine": false,
            "medicineNote": null,
            "hazardoussubstances": null,
            "hazardoussubstancesNote": null,
            "other": null,
            "otherNote": null
          },
          "menstrualHistory": {
            "id": 29751531.046115115,
            "menarche": "laboris esse dolore",
            "menstrualCycle": "cillum sed ullamco",
            "menstrualPeriod": "velit magna",
            "menstrualVolume": "nisi anim ea esse dolor",
            "dysmenorrhea": false,
            "dysmenorrheaNote": null
          },
          "transfusionHistory": null,
          "ultrasounds": [
            "in Ut dolor aute",
            "id"
          ],
          "riskRecords": [
            "Duis",
            "nostrud magna eiusmod pariatur",
            "Ut",
            "dolor consequat"
          ],
          "packageorders": null,
          "devices": null,
          "doctor": null,
          "organization": null,
          "prenatalscreens": null,
          "prenatalvisits": null,
          "bloodPressures": null,
          "bloodOxygens": null,
          "bloodGlucoses": null,
          "weights": null,
          "temperatures": null
        }
      },
      {
        "id": 5808385.3835686445,
        "gravidityindex": -49021062.38370609,
        "year": "consectetur ea fugiat",
        "month": "aute id",
        "term": null,
        "vaginalDelivery": null,
        "cesareanSection": null,
        "forceps": null,
        "vacuumAssisted": null,
        "breechMidwifery": null,
        "puerperalFever": null,
        "hemorrhage": null,
        "abortion": null,
        "abortionNote": null,
        "medicalAbortion": null,
        "surgicalAbortion": null,
        "naturalAbortion": null,
        "currettage": null,
        "stillbirth": null,
        "fetusdeath": null,
        "inducedLabor": null,
        "ectopicPregnancy": null,
        "hydatidMole": null,
        "multiple": null,
        "fetalcount": null,
        "hospital": null,
        "complication": null,
        "complicationNote": null,
        "exceptionalcase": null,
        "note": null,
        "pregnancy": {
          "id": -24699860.783948362,
          "outpatientNO": "in exercitation cillum",
          "inpatientNO": null,
          "checkupNO": null,
          "insuranceType": null,
          "name": "sint",
          "age": -65670495.647278406,
          "gender": null,
          "dob": "ea pariatur ",
          "idType": 35462018.65218052,
          "idNO": "et veniam",
          "nationality": "voluptate aute veniam q",
          "nativeplace": "labore",
          "ethnic": "do",
          "telephone": "consequat nisi ex irure enim",
          "maritalStatus": 47162754.67691454,
          "nearRelation": true,
          "maritalYears": -2581769.143972546,
          "education": null,
          "occupation": "Excepteur et ea dolore nulla",
          "workplace": null,
          "workPhone": null,
          "occupationDetail": null,
          "familyIncome": null,
          "residenceAddress": "ad aliqua",
          "permanentResidenceAddress": "qui in non",
          "postpartumAddress": "labore consequat",
          "partnerName": "eu ea",
          "partnerGender": "Excepteur veniam minim dolore",
          "partnerDob": "aute eiusm",
          "partnerIdType": -83883696.95584336,
          "partnerIdNO": "amet nulla laborum",
          "partnerNationality": "id veniam eiusmod in p",
          "partnerNativeplace": "in velit",
          "partnerEthnic": "aliqua elit proident",
          "partnerTelephone": "pariatur",
          "partnerOccupation": "consequat",
          "partnerWorkplace": null,
          "partnerOccupationDetail": null,
          "lmp": "amet deserunt officia id labore",
          "edd": "tempor quis aliqua",
          "sureEdd": "deserunt eu",
          "gravidity": -26383853.060187563,
          "parity": -83113661.44098163,
          "gestationalWeek": null,
          "createDate": null,
          "modifyDate": null,
          "validateDate": null,
          "note": null,
          "recordsrc": null,
          "recordstate": null,
          "referral": null,
          "familyHistory": {
            "id": 59648875.78413066,
            "hypertension": false,
            "hypertensionNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": null,
            "cardiacDiseaseNote": null,
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": null,
            "diabetesNote": null,
            "birthdefects": null,
            "birthdefectsNote": null,
            "other": null,
            "otherNote": null
          },
          "procedureHistory": null,
          "diseaseHistory": {
            "id": 31552659.044078186,
            "hypertension": true,
            "hypertensionNote": "aliqua aliquip est id",
            "nephropathy": null,
            "nephropathyNote": null,
            "respiratoryDisease": null,
            "respiratoryDiseaseNote": null,
            "gastroDisease": null,
            "gastroDiseaseNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": false,
            "cardiacDiseaseNote": "do in irure aliquip qui",
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": false,
            "diabetesNote": "dolor",
            "other": null,
            "otherNote": null
          },
          "allergyHistory": null,
          "partnerProfile": {
            "id": -11363206.175975323,
            "outpatientNO": "in ut velit cupidatat",
            "smoke": true,
            "smokeNote": "nisi veniam",
            "alcohol": true,
            "alcoholNote": "elit Excepteur id",
            "aBO": null,
            "rH": null,
            "disease": "dolore in"
          },
          "personalProfile": {
            "id": -84855363.25369675,
            "preheight": null,
            "preweight": -63875508.36351874,
            "bmi": null,
            "smoke": false,
            "smokeNote": "voluptate Ut",
            "alcohol": false,
            "alcoholNote": "cillum nulla",
            "aBO": null,
            "rH": null,
            "radioactivity": false,
            "radioactivityNote": "eiusmod et nulla laborum sunt",
            "medicine": false,
            "medicineNote": null,
            "hazardoussubstances": null,
            "hazardoussubstancesNote": null,
            "other": null,
            "otherNote": null
          },
          "menstrualHistory": {
            "id": -38355418.90903071,
            "menarche": "in esse culpa",
            "menstrualCycle": "amet sed minim",
            "menstrualPeriod": "enim",
            "menstrualVolume": "labore",
            "dysmenorrhea": false,
            "dysmenorrheaNote": null
          },
          "transfusionHistory": null,
          "ultrasounds": [
            "laboris do ipsum commodo",
            "nostrud aliquip nulla labore Duis",
            "ad Duis sunt",
            "aute velit id",
            "fugiat"
          ],
          "riskRecords": [
            "minim consequat non pariatur",
            "des",
            "id"
          ],
          "packageorders": null,
          "devices": null,
          "doctor": null,
          "organization": null,
          "prenatalscreens": null,
          "prenatalvisits": null,
          "bloodPressures": null,
          "bloodOxygens": null,
          "bloodGlucoses": null,
          "weights": null,
          "temperatures": null
        }
      },
      {
        "id": 59606102.97325322,
        "gravidityindex": -21529963.76549509,
        "year": "aliqua ut ut cillum Ut",
        "month": "exercitation aliquip et",
        "term": null,
        "vaginalDelivery": null,
        "cesareanSection": null,
        "forceps": null,
        "vacuumAssisted": null,
        "breechMidwifery": null,
        "puerperalFever": null,
        "hemorrhage": null,
        "abortion": null,
        "abortionNote": null,
        "medicalAbortion": null,
        "surgicalAbortion": null,
        "naturalAbortion": null,
        "currettage": null,
        "stillbirth": null,
        "fetusdeath": null,
        "inducedLabor": null,
        "ectopicPregnancy": null,
        "hydatidMole": null,
        "multiple": null,
        "fetalcount": null,
        "hospital": null,
        "complication": null,
        "complicationNote": null,
        "exceptionalcase": null,
        "note": null,
        "pregnancy": {
          "id": 32471886.491636768,
          "outpatientNO": "nisi laborum",
          "inpatientNO": null,
          "checkupNO": null,
          "insuranceType": null,
          "name": "nulla dolor",
          "age": 64043770.87378022,
          "gender": null,
          "dob": "anim ut enim ullamco labore",
          "idType": -4283834.862860873,
          "idNO": "pariatur sit sun",
          "nationality": "cupidatat sed Lorem pariatur",
          "nativeplace": "in incididunt veniam pariatur minim",
          "ethnic": "voluptate ad aliqua",
          "telephone": "irure cupidatat",
          "maritalStatus": 47015711.2773577,
          "nearRelation": false,
          "maritalYears": 91885569.65685204,
          "education": null,
          "occupation": "do",
          "workplace": null,
          "workPhone": null,
          "occupationDetail": null,
          "familyIncome": null,
          "residenceAddress": "culpa consectetur reprehenderit",
          "permanentResidenceAddress": "esse magna nisi id",
          "postpartumAddress": "ipsum in",
          "partnerName": "laboris aliqua minim pariatur velit",
          "partnerGender": "esse dolore in non officia",
          "partnerDob": "deserunt ea",
          "partnerIdType": 722598.3168348968,
          "partnerIdNO": "ad nulla ut",
          "partnerNationality": "ut tempor sed incididunt",
          "partnerNativeplace": "Lorem quis",
          "partnerEthnic": "non",
          "partnerTelephone": "sunt",
          "partnerOccupation": "consequat",
          "partnerWorkplace": null,
          "partnerOccupationDetail": null,
          "lmp": "Duis consectetur velit occaecat",
          "edd": "pariatur",
          "sureEdd": "nostrud amet occaecat esse dolore",
          "gravidity": 30252162.066105142,
          "parity": 44166316.585229814,
          "gestationalWeek": null,
          "createDate": null,
          "modifyDate": null,
          "validateDate": null,
          "note": null,
          "recordsrc": null,
          "recordstate": null,
          "referral": null,
          "familyHistory": {
            "id": -85692169.30109009,
            "hypertension": false,
            "hypertensionNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": null,
            "cardiacDiseaseNote": null,
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": null,
            "diabetesNote": null,
            "birthdefects": null,
            "birthdefectsNote": null,
            "other": null,
            "otherNote": null
          },
          "procedureHistory": null,
          "diseaseHistory": {
            "id": 16609321.857107103,
            "hypertension": true,
            "hypertensionNote": "in ex",
            "nephropathy": null,
            "nephropathyNote": null,
            "respiratoryDisease": null,
            "respiratoryDiseaseNote": null,
            "gastroDisease": null,
            "gastroDiseaseNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": true,
            "cardiacDiseaseNote": "eu proi",
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": true,
            "diabetesNote": "dolor ex",
            "other": null,
            "otherNote": null
          },
          "allergyHistory": null,
          "partnerProfile": {
            "id": -82217044.97522344,
            "outpatientNO": "l",
            "smoke": true,
            "smokeNote": "proident commodo fugiat sed occaecat",
            "alcohol": true,
            "alcoholNote": "esse exercitation eu in",
            "aBO": null,
            "rH": null,
            "disease": "veniam do pariatur"
          },
          "personalProfile": {
            "id": 38294045.178129286,
            "preheight": null,
            "preweight": -45372039.33086689,
            "bmi": null,
            "smoke": true,
            "smokeNote": "ullamco in cupidatat ut nostrud",
            "alcohol": true,
            "alcoholNote": "repre",
            "aBO": null,
            "rH": null,
            "radioactivity": false,
            "radioactivityNote": "cupidatat",
            "medicine": false,
            "medicineNote": null,
            "hazardoussubstances": null,
            "hazardoussubstancesNote": null,
            "other": null,
            "otherNote": null
          },
          "menstrualHistory": {
            "id": 81384952.915337,
            "menarche": "voluptate in fugiat",
            "menstrualCycle": "est magna mollit consectetur",
            "menstrualPeriod": "reprehenderit",
            "menstrualVolume": "labore ut occaecat",
            "dysmenorrhea": false,
            "dysmenorrheaNote": null
          },
          "transfusionHistory": null,
          "ultrasounds": {
            "menopause": '6',
            "crl": 12,
            "nt": 35,
            "gestationalWeek": '23'
          },
          "riskRecords": [
            "sint Duis",
            "ipsum ullamco exercitation ad",
            "laborum aute dolore eu irure"
          ],
          "packageorders": null,
          "devices": null,
          "doctor": null,
          "organization": null,
          "prenatalscreens": null,
          "prenatalvisits": null,
          "bloodPressures": null,
          "bloodOxygens": null,
          "bloodGlucoses": null,
          "weights": null,
          "temperatures": null
        }
      },
      {
        "id": 91219260.57702187,
        "gravidityindex": -71526695.9592161,
        "year": "consectetur",
        "month": "sit Lorem aliquip velit commodo",
        "term": null,
        "vaginalDelivery": null,
        "cesareanSection": null,
        "forceps": null,
        "vacuumAssisted": null,
        "breechMidwifery": null,
        "puerperalFever": null,
        "hemorrhage": null,
        "abortion": null,
        "abortionNote": null,
        "medicalAbortion": null,
        "surgicalAbortion": null,
        "naturalAbortion": null,
        "currettage": null,
        "stillbirth": null,
        "fetusdeath": null,
        "inducedLabor": null,
        "ectopicPregnancy": null,
        "hydatidMole": null,
        "multiple": null,
        "fetalcount": null,
        "hospital": null,
        "complication": null,
        "complicationNote": null,
        "exceptionalcase": null,
        "note": null,
        "pregnancy": {
          "id": 56303661.61643621,
          "outpatientNO": "aliqua laboris nisi",
          "inpatientNO": null,
          "checkupNO": null,
          "insuranceType": null,
          "name": "laboris fugiat Lorem ut",
          "age": 25562870.348318562,
          "gender": null,
          "dob": "eu elit Excepteur",
          "idType": 42525069.769905776,
          "idNO": "officia voluptate",
          "nationality": "reprehenderit aute do",
          "nativeplace": "nostrud pariatur dolor dolore",
          "ethnic": "null",
          "telephone": "exercitation",
          "maritalStatus": -99094483.98989382,
          "nearRelation": false,
          "maritalYears": 76286701.54644471,
          "education": null,
          "occupation": "Lorem exercitation est nulla laborum",
          "workplace": null,
          "workPhone": null,
          "occupationDetail": null,
          "familyIncome": null,
          "residenceAddress": "in in sunt laborum ea",
          "permanentResidenceAddress": "proident fugiat veniam",
          "postpartumAddress": "laboris",
          "partnerName": "sint minim veniam nisi sed",
          "partnerGender": "eu consectetur irure",
          "partnerDob": "sunt dolor",
          "partnerIdType": 38872507.79045504,
          "partnerIdNO": "aute labore",
          "partnerNationality": "in",
          "partnerNativeplace": "dolore Duis",
          "partnerEthnic": "veniam consectetur aute nisi",
          "partnerTelephone": "fugiat minim laborum",
          "partnerOccupation": "tempor",
          "partnerWorkplace": null,
          "partnerOccupationDetail": null,
          "lmp": "fugiat tempor sunt incididunt culpa",
          "edd": "sun",
          "sureEdd": "nostrud",
          "gravidity": -99262433.05997166,
          "parity": 40814240.205473095,
          "gestationalWeek": null,
          "createDate": null,
          "modifyDate": null,
          "validateDate": null,
          "note": null,
          "recordsrc": null,
          "recordstate": null,
          "referral": null,
          "familyHistory": {
            "id": 42543495.47002131,
            "hypertension": false,
            "hypertensionNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": null,
            "cardiacDiseaseNote": null,
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": null,
            "diabetesNote": null,
            "birthdefects": null,
            "birthdefectsNote": null,
            "other": null,
            "otherNote": null
          },
          "procedureHistory": null,
          "diseaseHistory": {
            "id": 72934984.5005045,
            "hypertension": true,
            "hypertensionNote": "",
            "nephropathy": null,
            "nephropathyNote": null,
            "respiratoryDisease": null,
            "respiratoryDiseaseNote": null,
            "gastroDisease": null,
            "gastroDiseaseNote": null,
            "hepaticDisease": null,
            "hepaticDiseaseNote": null,
            "epilepsy": null,
            "epilepsyNote": null,
            "cardiacDisease": true,
            "cardiacDiseaseNote": "irure",
            "endocrineDisease": null,
            "endocrineDiseaseNote": null,
            "thyroidDisease": null,
            "thyroidDiseaseNote": null,
            "hematopathy": null,
            "hematopathyNote": null,
            "mentalDisease": null,
            "mentalDiseaseNote": null,
            "diabetes": true,
            "diabetesNote": "sed minim officia labore ipsum",
            "other": null,
            "otherNote": null
          },
          "allergyHistory": null,
          "partnerProfile": {
            "id": -89361319.99345824,
            "outpatientNO": "ea",
            "smoke": true,
            "smokeNote": "proident et labore tempor commodo",
            "alcohol": true,
            "alcoholNote": "fugiat dol",
            "aBO": null,
            "rH": null,
            "disease": "ut dolor est dolore"
          },
          "personalProfile": {
            "id": -52811416.35507223,
            "preheight": null,
            "preweight": -42700338.0216457,
            "bmi": null,
            "smoke": true,
            "smokeNote": "cupidatat fugiat adipisicing",
            "alcohol": false,
            "alcoholNote": "Lorem amet ex nulla",
            "aBO": null,
            "rH": null,
            "radioactivity": true,
            "radioactivityNote": "voluptate fugiat laborum",
            "medicine": false,
            "medicineNote": null,
            "hazardoussubstances": null,
            "hazardoussubstancesNote": null,
            "other": null,
            "otherNote": null
          },
          "menstrualHistory": {
            "id": -95520533.45580767,
            "menarche": "exe",
            "menstrualCycle": "enim cupidatat ut",
            "menstrualPeriod": "irure minim tempor veniam ",
            "menstrualVolume": "non in tempor",
            "dysmenorrhea": false,
            "dysmenorrheaNote": null
          },
          "transfusionHistory": null,
          "ultrasounds": [
            "occaecat consequat eu adipisicing qui",
            "magna enim Lorem nisi cillum",
            "dolor aute ipsum amet do",
            "nostrud commodo in ut sint",
            "m"
          ],
          "riskRecords": [
            "elit irure",
            "sint",
            "adipisicing",
            "esse in Duis elit consequat",
            "aliqua consectetur tempor cupidatat culpa"
          ],
          "packageorders": null,
          "devices": null,
          "doctor": null,
          "organization": null,
          "prenatalscreens": null,
          "prenatalvisits": null,
          "bloodPressures": null,
          "bloodOxygens": null,
          "bloodGlucoses": null,
          "weights": null,
          "temperatures": null
        }
      }
    ],
    "ultrasounds": [
      "mol"
    ],
    "riskRecords": [
      "et ut",
      "qui veniam in",
      "Excepteur laborum tempor",
      "nulla in esse commodo mollit",
      "sunt qui nulla"
    ],
    "packageorders": null,
    "devices": null,
    "doctor": null,
    "organization": null,
    "prenatalscreens": null,
    "bloodPressures": null,
    "bloodOxygens": null,
    "bloodGlucoses": null,
    "weights": null,
    "temperatures": null
  },
  "doctor": null,
  "ecgexam": null,
  "ctgexam": {
    "id": -20250366.599516362,
    "startTime": null,
    "endTime": null,
    "result": null,
    "note": "sit",
    "diagnosis": null,
    "report": null
  }
}

export default data;
